import './globals.css'
import { inter } from '@/app/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='bg-white' lang='en'>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  )
}
